
"enable mouse support
if has('mouse')      
    set mouse=a      
endif                

" turn off indentation when you paste into vim        
let &t_SI .= "\<Esc>[?2004h"                          
let &t_EI .= "\<Esc>[?2004l"                          
                                                      
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
                                                      
function! XTermPasteBegin()                           
  set pastetoggle=<Esc>[201~                          
  set paste                                           
  return ""                                           
endfunction                                           
                                                      
fun! TrimWS()                                         
        let l:save = winsaveview()                    
        keeppatterns %s/\s\+$//e                      
        call winrestview(l:save)                      
endfun                                                

